from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.pagesizes import letter

from datetime import datetime

# =====================================================
# PDF GENERATOR
# =====================================================

def generate_pdf_report(
    filepath,
    result,
    confidence,
    risk_level,
    trust_score,
    verification_status,
    recommendation,
    signals,
    verification_signals
):

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # ==========================================
    # TITLE
    # ==========================================

    elements.append(
        Paragraph(
            "JobShield AI - Fraud Analysis Report",
            styles['Title']
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================================
    # TIMESTAMP
    # ==========================================

    elements.append(
        Paragraph(
            f"Generated On: {datetime.now()}",
            styles['Normal']
        )
    )

    elements.append(Spacer(1, 20))

    # ==========================================
    # MAIN RESULTS
    # ==========================================

    report_data = [

        f"<b>Prediction:</b> {result}",

        f"<b>Confidence:</b> {confidence}%",

        f"<b>Risk Level:</b> {risk_level}",

        f"<b>Trust Score:</b> {trust_score}%",

        f"<b>Verification Status:</b> {verification_status}",

        f"<b>Recommendation:</b> {recommendation}"
    ]

    for item in report_data:

        elements.append(
            Paragraph(item, styles['BodyText'])
        )

        elements.append(Spacer(1, 12))

    # ==========================================
    # DETECTED SIGNALS
    # ==========================================

    elements.append(
        Paragraph(
            "<b>Detected Signals:</b>",
            styles['Heading2']
        )
    )

    for signal in signals:

        elements.append(
            Paragraph(
                f"• {signal}",
                styles['BodyText']
            )
        )

    elements.append(Spacer(1, 20))

    # ==========================================
    # VERIFICATION SIGNALS
    # ==========================================

    elements.append(
        Paragraph(
            "<b>Verification Signals:</b>",
            styles['Heading2']
        )
    )

    for signal in verification_signals:

        elements.append(
            Paragraph(
                f"• {signal}",
                styles['BodyText']
            )
        )

    elements.append(Spacer(1, 20))

    # ==========================================
    # FOOTER
    # ==========================================

    elements.append(
        Paragraph(
            "Generated by JobShield AI Recruitment Security Platform",
            styles['Italic']
        )
    )

    doc.build(elements)